/**
 * The block.
 *
 * The PHPUnit suite already proves the render callback returns the same markup
 * the shortcode returns, and that rendering records nobody, so repeating any of
 * that here would buy nothing. What only a browser can answer is whether the
 * *built* JavaScript works: `build/` is generated by bin/build and is not in the
 * repository, so every assertion below is also an assertion that the build ran
 * and produced something a browser can load.
 *
 * Two things are worth a browser, and nothing else here is:
 *
 * * the editor script loads and registers the block -- a broken build, a
 *   missing dependency in index.asset.php or a bad block.json all show up here
 *   and nowhere else;
 * * a post holding the block comment renders the listing on the front end,
 *   which is the only place the saved-name-to-callback wiring is exercised by
 *   something that saved the name itself.
 *
 * The editor preview is the same request in a different suit: it is core's
 * ServerSideRender posting to /wp/v2/block-renderer/, so seeing the listing
 * there is what proves the block earns no REST route of its own.
 */

const { test, expect } = require( '@wordpress/e2e-test-utils-playwright' );
const {
	asGuest,
	insertOnline,
	truncateOnline,
	uniqueTitle,
} = require( './helpers.js' );

/** The one block this plugin registers. */
const BLOCK = 'wp-useronline/page-useronline';

test.describe( 'The block', () => {
	test.beforeEach( () => {
		truncateOnline();
	} );

	test.describe( 'in the editor', () => {
		test( 'it is registered, under the prefixed name', async ( {
			admin,
			editor,
			page,
		} ) => {
			await admin.createNewPost();
			await editor.canvas.locator( 'body' ).waitFor();

			const names = await page.evaluate( () =>
				window.wp.blocks.getBlockTypes().map( ( type ) => type.name ),
			);

			// If the build did not run, or index.asset.php named a dependency
			// that does not exist, the editor script never executes and the
			// name is not here -- which is the failure this whole file exists
			// for.
			expect( names ).toContain( BLOCK );

			// The prefix is not decoration: a block name is written into
			// post_content and lives there for the life of the post.
			expect( names ).not.toContain( 'useronline/page-useronline' );
		} );

		test( 'it previews the listing it would render', async ( {
			admin,
			editor,
		} ) => {
			insertOnline( {
				userType: 'member',
				userId: 5,
				userName: 'Ada',
				userIp: '203.0.113.11',
			} );

			await admin.createNewPost();
			await editor.insertBlock( { name: BLOCK } );

			// Core's ServerSideRender, which posts to /wp/v2/block-renderer/ and
			// draws what the front end would draw. This is the endpoint that
			// makes a REST namespace of the plugin's own unnecessary for the
			// block.
			const details = editor.canvas.locator( '#useronline-details' );

			await expect( details ).toBeVisible();
			await expect( details ).toContainText( 'Ada' );
			await expect( details ).toContainText( 'Most users ever online were' );
		} );
	} );

	test.describe( 'on the front end', () => {
		test( 'a post holding the block renders the listing', async ( {
			page,
			requestUtils,
		} ) => {
			const post = await requestUtils.createPost( {
				title: uniqueTitle( 'Who is online, in a block' ),
				content: `<!-- wp:${ BLOCK } /-->`,
				status: 'publish',
			} );

			// As a guest, because the listing shows addresses and wp-admin URLs
			// only to whoever holds the details capability, and the suite's own
			// browser is signed in as an administrator.
			await asGuest( page, {}, async ( guest ) => {
				await guest.goto( post.link );

				const details = guest.locator( '#useronline-details' );

				await expect( details ).toBeVisible();
				// The guest was recorded by wp_head before the content rendered,
				// so the listing they are reading has them in it.
				await expect( details ).toContainText( '1 Guest Online Now' );
			} );
		} );
	} );
} );
